# Generated by Django 5.0.6 on 2024-05-24 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='client.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='client.application'),
        ),
    ]
