# Generated by Django 5.0.6 on 2024-05-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_deal_client_alter_deal_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
